### ISSUE TITLE
basecall_grp parameter

### ISSUE THREAD

**Issue by swiddison** [popitsch/nanopanel2#1]
I have looked through all my output files from Guppy and can't see where the basecall_grp information is stored. Can you advise where I can find it please.

**Comment by popitsch** [comment]
Hi,
The configuration property “basecall_grp” should be set to the respective name used as a key in the FAST5 output files of guppy which are in fact HDF5 files.
You can inspect HDF5 files, e.g., with ‘h5ls’ (see https://support.hdfgroup.org/products/hdf5_tools/).

Guppy will per default use ‘Basecall_1D_000’ for the first basecalling run you apply to these files,  ‘Basecall_1D_001’ for the second one aso.
So if you sequenced with MinKNOW  and configured basecalling and then manually ran guppy on the FAST5 files as described in the Nanopanel2 README, then  ‘Basecall_1D_001’ should work.
HTH, BW niko

From: swiddison ***@***.***>
Reply to: popitsch/nanopanel2 ***@***.***>
Date: Tuesday, 23. March 2021 at 18:30
To: popitsch/nanopanel2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [popitsch/nanopanel2] basecall_grp parameter (#1)


I have looked through all my output files from Guppy and can't see where the basecall_grp information is stored. Can you advise where I can find it please.

**Comment by swiddison** [comment]
Great thanks
