### ISSUE TITLE
Fast5 files split by barcode

### ISSUE THREAD

**Issue by swiddison** [popitsch/nanopanel2#2]
I have barcoded reads which are being demultiplexed correctly by Porechop but my Fast5 files are not loading.
From the log file:
Reading FAST5 files from fast5_pass/
INFO:root:Loaded 0 FAST5 files

From looking at the code I suspect this may be because my fast5 reads are in separate subfolders by barcode within the folder I specify in the config (fast5_pass).
The contents of fast5_pass looks like:
barcode01/
barcode02/
etc....
With the .fast5 reads for each barcode within their own folder.

**Comment by popitsch** [comment]
Hi swiddison, did you demultiplex yourself or via nanopanel2? 
Both is possible but if you demultiplex yourself then you need to configure each sample individually as np2 will not know how to access the individual samples. If you let np2 do the demultiplexing (currently we support only porechop) then you can add the "demultiplex" section to the config file (see the example config file) and you should get individual output files per sample. A simple 'demultiplex' configuration section looks like this:
"demultiplex": {
                "BC01": "S01",
                 [...]
                 "BC12": "S12"
                },
Note that you will get output files only for found barcodes.

If this does not solve your issue, could you please post your config file?

**Comment by swiddison** [comment]
I had already demultiplexed, it looks like it will run if I supply one barcode but fails because trace logs were not used as an option in Guppy. Thanks for your help

**Comment by popitsch** [comment]
ok, thanks for your report - I have improved the README to make it clearer how to work with multiplexed datasets.

**Comment by swiddison** [comment]
I have now redone basecalling with Guppy using your suggested parameters (--trace_categories_logs Move, but I also tried --trace_categories_logs Move, Trace) and I am still getting an error about the Trace file being missing as shown below. This is for one of the demultiplexed sets of fast5 files. The guppy version I am using is 3.4.1.
 
Extracting FASTQ data for all: 100%|█████████████████████████████████████████████████████████████████████| 22/22 [01:03<00:00,  2.89s/it]
Decorating reads in all/mm2:   0%|                                                                             | 0/89437 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/nanopanel2/nanopanel2.py", line 2077, in <module>
    nanopanel2_pipeline(config, outdir)
  File "/nanopanel2/nanopanel2.py", line 2007, in nanopanel2_pipeline
    decorate_reads(config, samples)
  File "/nanopanel2/nanopanel2.py", line 677, in decorate_reads
    trace = np.array(h5_file[rid]["Analyses"][bcg]["BaseCalled_template"]["Trace"])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Trace' doesn't exist)"

I confirmed that my fast5 files have the Move and Trace logs:
DATASET "Move" {
                  DATATYPE  H5T_STD_U8LE
                  DATASPACE  SIMPLE { ( 3336 ) / ( 3336 ) }
                  DATA {
...
               DATASET "Trace" {
                  DATATYPE  H5T_STD_U8LE
                  DATASPACE  SIMPLE { ( 3336, 8 ) / ( 3336, 8 ) }
                  DATA {

**Comment by popitsch** [comment]
Hi
Np2 was tested/developed with guppy 3.6.1 (see README), so don’t know whether it will work with 3.4.1 files.

Could you try the following with python3 (tested this code with 3.7.2) please?

import h5py

def print_keys_recursive(a, pad=''):

    if hasattr(a, 'keys'):

        for k in list(a.keys()):

            print(pad, k)

            if k in a:

                print_keys_recursive(a[k], pad+'  ')

def print_keys(fast5_file):

    f = h5py.File(fast5_file, 'r')

    first_read_name=next(iter(f.keys()))

    print_keys_recursive(f[first_read_name])

and the run
print_keys(<my_fast5_file_path>)

Below is an example of a FAST5 files that was basecalled 2 times:
- Data from the first run is under key ‘Basecall_1D_000’ w/o the required Move and Trace fields.
- Data form the second run is under key ‘Basecall_1D_001’ including Move and Trace data.
- So "basecall_grp" should be set to "Basecall_1D_001" in the np2 config

>>> print_keys('ACH674_pass_6a45930b_45.fast5')
Analyses
   Basecall_1D_000
     BaseCalled_template
       Fastq
     Summary
       basecall_1d_template
   Basecall_1D_001
     BaseCalled_template
       Fastq
       Move
       Trace
     Summary
       basecall_1d_template
   Segmentation_000
     Summary
       segmentation
   Segmentation_001
     Summary
       segmentation
Raw
   Signal
channel_id
context_tags
tracking_id



From: swiddison ***@***.***>
Reply to: popitsch/nanopanel2 ***@***.***>
Date: Tuesday, 30. March 2021 at 13:12
To: popitsch/nanopanel2 ***@***.***>
Cc: "Popitsch,Niko" ***@***.***>, State change ***@***.***>
Subject: Re: [popitsch/nanopanel2] Fast5 files split by barcode (#2)


I have now redone basecalling with Guppy using your suggested parameters (--trace_categories_logs Move, but I also tried --trace_categories_logs Move, Trace) and I am still getting an error about the Trace file being missing as shown below. This is for one of the demultiplexed sets of fast5 files. The guppy version I am using is 3.4.1.

Extracting FASTQ data for all: 100%|█████████████████████████████████████████████████████████████████████| 22/22 [01:03<00:00, 2.89s/it]
Decorating reads in all/mm2: 0%| | 0/89437 [00:00<?, ?it/s]Traceback (most recent call last):
File "/nanopanel2/nanopanel2.py", line 2077, in
nanopanel2_pipeline(config, outdir)
File "/nanopanel2/nanopanel2.py", line 2007, in nanopanel2_pipeline
decorate_reads(config, samples)
File "/nanopanel2/nanopanel2.py", line 677, in decorate_reads
trace = np.array(h5_file[rid]["Analyses"][bcg]["BaseCalled_template"]["Trace"])
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in getitem
oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Trace' doesn't exist)"

I confirmed that my fast5 files have the Move and Trace logs:
DATASET "Move" {
DATATYPE H5T_STD_U8LE
DATASPACE SIMPLE { ( 3336 ) / ( 3336 ) }
DATA {
...
DATASET "Trace" {
DATATYPE H5T_STD_U8LE
DATASPACE SIMPLE { ( 3336, 8 ) / ( 3336, 8 ) }
DATA {

**Comment by swiddison** [comment]
Changing the Basecall group to  Basecall_1D_001 fixed the issue, thanks.
