### ISSUE TITLE
Regions of interest Bed

### ISSUE THREAD

**Issue by swiddison** [popitsch/nanopanel2#3]
In the block diagram it lists a regions of interest bed as an optional input file but I can't see how to specify it. There is a line in the config for roi_intervals though.
Is it possible to supply a bed file of individual snp locations to only call snps at those positions?

**Comment by popitsch** [comment]
In the config, you can either specify a list of genomic intervals ("roi_intervals": ['chr1:1-2','chr2:3-4']) or a BED file ("roi_file": "myfile.bed") which will override the 'roi_intervals' configuration. Usually this is done to exclude regions at the amplicon borders.
