### ISSUE TITLE
Genotype always 1

### ISSUE THREAD

**Issue by swiddison** [popitsch/nanopanel2#4]
In the vcf file is the genotype always set to 1 no matter the value for VAF_CORR= as long as the allele frequency is above the threshold of 1%?

**Comment by popitsch** [comment]
yes, currently GT is by default always set to 0/1 for compatibility with downstream tools that require this field to be set (you can turn this off by setting 'add_gt_field' to false in the config) but please note that this does not reflect the actual genotype for somatic variants.
