### ISSUE TITLE
KeyError: "Unable to open object (object 'Trace' doesn't exist)"

### ISSUE THREAD

**Issue by BioWilko** [popitsch/nanopanel2#7]
I'm getting this error when I try to run your tool, I'm not sure if it's something screwy with my config file or what....

I'm running on the singularity image if that helps.

Here's the error:

> Extracting FASTQ data for all: 100%|███████████████████████████| 50/50 [00:57<00:00,  1.14s/it]
> Decorating reads in all/mm2:   0%|                                  | 0/192821 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "/nanopanel2/nanopanel2.py", line 2077, in <module>
>     nanopanel2_pipeline(config, outdir)
>   File "/nanopanel2/nanopanel2.py", line 2007, in nanopanel2_pipeline
>     decorate_reads(config, samples)
>   File "/nanopanel2/nanopanel2.py", line 677, in decorate_reads
>     trace = np.array(h5_file[rid]["Analyses"][bcg]["BaseCalled_template"]["Trace"])
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/group.py", line 264, in __getitem__
>     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 190, in h5py.h5o.open
> KeyError: "Unable to open object (object 'Trace' doesn't exist)"

It seems to be where the decorated bam index file is getting generated since that's the only missing file as far as I can tell.

**Comment by popitsch** [comment]
Hi
Can you please check whether your FAST5 files contain the following sections:
[read_id]["Analyses"][basecall_grp]["BaseCalled_template"]["Trace"] and
[read_id]["Analyses"][basecall_grp]["BaseCalled_template"]["Move"].
These sections are added by guppy 3.6.1 with the '--trace_categories_logs Move' parameter set (see README).

One way to check what sections your FAST5 contains is to run the following in a python3.7 console (with h5py installed):
```
import h5py

def print_h5_keys_recursive(a, pad=''):
    if hasattr(a, 'keys'):
        for k in list(a.keys()):
            print(pad, k)
            if k in a:
                print_h5_keys_recursive(a[k], pad+'  ')

def print_h5_keys(fast5_file):
    """ print an exemplary h5 key structure for the passed fast5 files """
    f = h5py.File(fast5_file, 'r')
    first_read_name=next(iter(f.keys()))
    print_h5_keys_recursive(f[first_read_name])

print_h5_keys('myfile.fast5') # replace by one of your FAST5 filenames here
```

Unfortunately, the Event table was removed from FAST5 by later versions of guppy (see discussions in the Nanopore community) so if you use a newer version you'd need to redo base-calling with guppy 3.6.1 to get np2 to run.

**Comment by Trandamere** [comment]
hello:
I have the same problem.The software has a good future, provided it supports the new version of Guppy.This forced me to give it up.
